/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

public class MapadeMesas extends javax.swing.JFrame {

    /**
     * Creates new form TeladeMesas
     */
    public MapadeMesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jButton109 = new javax.swing.JButton();

        jButton49.setBackground(new java.awt.Color(204, 204, 204));
        jButton49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton49.setBorder(null);

        jButton50.setBackground(new java.awt.Color(204, 204, 204));
        jButton50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton50.setBorder(null);

        jButton51.setBackground(new java.awt.Color(204, 204, 204));
        jButton51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton51.setBorder(null);

        jButton52.setBackground(new java.awt.Color(204, 204, 204));
        jButton52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton52.setBorder(null);

        jButton53.setBackground(new java.awt.Color(204, 204, 204));
        jButton53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton53.setBorder(null);

        jButton54.setBackground(new java.awt.Color(204, 204, 204));
        jButton54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton54.setBorder(null);

        jButton67.setBackground(new java.awt.Color(204, 204, 204));
        jButton67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton67.setBorder(null);

        jButton68.setBackground(new java.awt.Color(204, 204, 204));
        jButton68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton68.setBorder(null);

        jButton69.setBackground(new java.awt.Color(204, 204, 204));
        jButton69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton69.setBorder(null);

        jButton70.setBackground(new java.awt.Color(204, 204, 204));
        jButton70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton70.setBorder(null);

        jButton71.setBackground(new java.awt.Color(204, 204, 204));
        jButton71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton71.setBorder(null);

        jButton72.setBackground(new java.awt.Color(204, 204, 204));
        jButton72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton72.setBorder(null);

        jButton111.setBackground(new java.awt.Color(204, 204, 204));
        jButton111.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton111.setForeground(new java.awt.Color(255, 153, 0));
        jButton111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-mesa-96.png"))); // NOI18N
        jButton111.setText("Mesa1");
        jButton111.setBorder(null);
        jButton111.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton111.setIconTextGap(-25);
        jButton111.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton111.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton111ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Sair");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jButton109.setBackground(new java.awt.Color(204, 204, 204));
        jButton109.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButton109.setForeground(new java.awt.Color(255, 153, 0));
        jButton109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-comida-96.png"))); // NOI18N
        jButton109.setText("Mesa1");
        jButton109.setBorder(null);
        jButton109.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton109.setIconTextGap(-25);
        jButton109.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton109.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton109ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton109, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1075, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton109)
                .addContainerGap(435, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton109ActionPerformed
       Integer idmesa=8;
    TelaMesas tela=new TelaMesas(idmesa);
    tela.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jButton109ActionPerformed

    private void jButton111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton111ActionPerformed
     Integer idmesa=10;
    TelaMesas tela=new TelaMesas(idmesa);
    tela.setVisible(true);   // TODO add your handling code here:
    }//GEN-LAST:event_jButton111ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapadeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapadeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapadeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapadeMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapadeMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
